name: XIAOMI Signin

on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 16:20
    - cron: '20 17 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: XIAOMI Signin
    runs-on: ubuntu-latest
    steps:
      - uses: Devifish/sport-editor
        with:
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSH_TYPES: 'pushplus'
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
